baseurl = "https://inderjit.in"
DefaultContentLanguage = "en"
title = "Inderjit Singh Chahal"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-179098818-1"

[Params]
  homeTitle = "'Music of Reason'  Mathematics" # Set a different text for the header on the home page
  subtitle = "James Joseph Sylvester"
  mainSections = ["post","posts"]
  logo = "images/aa.jpg" 
  favicon = "img/me.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = false
  gcse = "2b9af657ac7ec4501" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic" 
  gtm_id = "G-PH5DZ65D73"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
[[Params.bigimg]]
  src = "images/del.gif"
  desc = "Inderjit Singh Chahal"

#for html in markdowns

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Author]
  name = "Inderjit Singh Chahal"
  website = ""
  email = "inder@inderjit.in"
  #facebook = "username"
  github = "chahalinder0007"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "Inderjitsingh08"
  reddit = "inderjitsinghchahal"
  linkedin = "indejitsinghchahal"
  #xing = "username"
  stackoverflow = "users/7805917/inder"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "Portfolio"
    url = "page/portfolio/"
    weight = 3

[[menu.main]]
    name = "Feedback"
    url = "page/feedback/"
    weight = 3